---
name: New community member suggestion
about: Item suggestion for new community member feed
title: Please include [Community member] in the feed generator
labels: members

---

Include community member details:
- Name: [Antonio Maradiaga]
- Username: [ajmaradiaga]
- Profile URL: [https://community.sap.com/t5/user/viewprofilepage/user-id/107]
