name: New topic suggestion
description: Item suggestion for new topic feed
title: "Please include [Topic name] in the feed generator"
labels: ["topic"]
body:
- type: textarea
  attributes:
    label: Topic details
    value: |
      - Name: [SAP Integration Suite]
      - URL: [https://pages.community.sap.com/topics/integration-suite]
      
      You can find all topics here: https://pages.community.sap.com/topics
