name: New community member suggestion
description: Item suggestion for new community member feed
title: Please include [SAP Community member] in the feed generator
labels: ["members"]
body:
  - type: textarea
    attributes:
      label: Community member details
      value: |
        - Name: [SAP Community member]
        - Username: [SAP Community member username]
        - Profile URL: [SAP Community member profile URL]
