name: New community member suggestion
description: Item suggestion for new community member feed
title: Please include [SAP Community member] in the feed generator
labels: members
body:
  Include community member details:
  - Name: [Antonio Maradiaga]
  - Username: [ajmaradiaga]
  - Profile URL: [https://community.sap.com/t5/user/viewprofilepage/user-id/107]
