---
name: New topic suggestion
about: Item suggestion for new topic feed
title: Please include [Topic name] in the feed generator
labels: topic

---

Add topic details:
- Name: [SAP Integration Suite]
- URL: [https://pages.community.sap.com/topics/integration-suite]

You can find all topics here: https://pages.community.sap.com/topics